services:
  server:
    build: .
    container_name: lightbroker-server
    ports:
      - "5555:5555"
    command: python -m lightbroker --server
  agent:
    build: .
    container_name: lightbroker-agent
    ports:
      - "5556:5556"
    command: python -m lightbroker --agent --agent-server 0.0.0.0
